language: go
go:
- 1.15
install:
- npm install -g bower
- cd ui/static && bower install && cd -
script:
- go build -o cf-wall
after_success:
- bin/build/all
deploy:
  provider: releases
  file:
  - _build/linux_amd64/cf-wall_linux_amd64.zip
  - _build/linux_386/cf-wall_linux_386.zip
  - _build/windows_amd64/cf-wall_windows_amd64.zip
  - _build/windows_386/cf-wall_windows_386.zip
  - _build/darwin_amd64/cf-wall_darwin_amd64.zip
  skip_cleanup: true
  on:
    tags: true
    repo: orange-cloudfoundry/cf-wall
  api-key:
    secure: j56yglq9+AblOdTrzMaw7pP2ChlkmpGzVfITvXD2gw0mTRNK6tJQlwt+DJ5SAE/EIgqZ/kjFEXlIAFVj0hu00E35olF+xkS5n/abER8aprEHKo21Ed4PDfSAnxe6OSpj7t5zbQbqkYu3eFYqIvL+Cj7D1b6EUJRC5A7FDG5IML0dJHGLalj+zC3XUBcE+qM7AB3AevNy3U8ggwMIMSTtJjvpgjORB/6iobbgX/ZaOARYEkgdsaNSBzfkTSx/cvx7AP4cPUwxs7ixLUqQU6R3O/+9OxIg9oktg+uY7gdmdjLljhaXySHYvMDcGZuEmppB1vcS4i1wx1/JMf5xYDEBc4uBCT+72rYJbIlHWfHZcuM6Ej/M6FEm81gJ8zniE0r4BrKQhI1M2y7ER/W/uO/UcZz8SOiG1DgsBOETkXGGtTAx3OKKH4Cef0EnDtBZIrjw4hTUCO8XN+Q8tHcQEon8s/wgTZdJzSQLXRr4d8Zx9uEe2/BH0tX1WZCQmCFGtWUrtpuEyE9Qruw45bY/IDqqKDZFFBNkPR/wYZN8VIO3Ma3z/NoosMhXxCdXPrM8Y4YaXF4SO5Kz6X0Sg9E835HpqyYHtNAt3vUSjs2ARYSACms23NvHQFGy3LwPEQkOA5HaPly61Puaqxx5VhxBZS41Vy4+j63/Zt7EzkDaU0ArI2s=
