required = [
  "github.com/cloudfoundry-community/go-cfclient",
  "github.com/gorilla/mux",
  "github.com/dgrijalva/jwt-go",
  "code.cloudfoundry.org/uaa-go-client"
]

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/uaa-go-client"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-community/go-cfclient"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  version = "v2.7.0"
  name = "github.com/dgrijalva/jwt-go"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/lager"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/clock"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/golang-commonmark/markdown"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry-community/gautocloud"

[[constraint]]
  name = "gopkg.in/gomail.v2"
