app_name: "cfy-wall"
services:
  - name: smtp-service
    tags: [smtp]
    credentials:
      host: ****
      port: 25

  - name: cfy-wall-config
    tags: []
    credentials:
      log-level: warning
